const sampleData = [
  {
    id: 281,
    user_name: 'Carmen_Monahan',
    restaurant_name: 'Schmitt and Sons',
    content: 'Est exercitationem perferendis possimus non veritatis ipsam voluptate id quo. Ut repellendus sit vel autem doloribus quam. Qui expedita molestiae pariatur velit repellendus at iste porro dolore. Fugit reprehenderit atque nesciunt maxime velit vitae praesentium. Beatae nulla aut sunt cupiditate qui sit praesentium. Nihil perspiciatis tempore.',
    rating: 2,
    delivery_rating: 2,
    order_rating: 5,
    update_date: '2018-12-17T08:00:00.000Z',
  },
  {
    id: 82,
    user_name: 'Elaina.Bernhard10',
    restaurant_name: 'Schmitt and Sons',
    content: 'Deserunt assumenda dolorem est numquam omnis minus. Id molestias culpa corrupti recusandae consectetur quia recusandae expedita. Nemo recusandae harum non blanditiis qui nisi doloremque adipisci est.',
    rating: 5,
    delivery_rating: 5,
    order_rating: 1,
    update_date: '2018-12-05T08:00:00.000Z',
  },
  {
    id: 134,
    user_name: 'Jordon.Schmidt',
    restaurant_name: 'Schmitt and Sons',
    content: 'Nihil asperiores repudiandae consequatur fuga. Dicta beatae temporibus repudiandae expedita atque nulla earum quidem. Nobis assumenda labore. Officia est sunt deleniti ullam aperiam quaerat in. Perferendis ratione enim quia atque. Sed est et fugiat quia recusandae quaerat veritatis ut quia.',
    rating: 3,
    delivery_rating: 4,
    order_rating: 1,
    update_date: '2018-11-05T08:00:00.000Z',
  },
  {
    id: 86,
    user_name: 'Rory.Dare79',
    restaurant_name: 'Schmitt and Sons',
    content: 'Molestiae cupiditate et deserunt voluptas. Eos magnam perferendis omnis id.',
    rating: 4,
    delivery_rating: 5,
    order_rating: 2,
    update_date: '2018-10-29T07:00:00.000Z',
  },
  {
    id: 5,
    user_name: 'Juanita63',
    restaurant_name: 'Schmitt and Sons',
    content: 'Architecto sequi officia ratione enim et et. Exercitationem quae voluptas consectetur hic amet fugiat. Eius excepturi harum consectetur fuga aliquam molestias dolor perspiciatis eum. Tempora fugit aut odit. Aspernatur sed quo. Maiores at ipsa.',
    rating: 5,
    delivery_rating: 2,
    order_rating: 3,
    update_date: '2018-10-21T07:00:00.000Z',
  },
  {
    id: 152,
    user_name: 'Terrence_Baumbach82',
    restaurant_name: 'Schmitt and Sons',
    content: 'Corrupti ut facilis saepe sunt quia quam voluptas. Libero tempora et autem rem magni tenetur sunt molestiae. Est facere doloribus. Eligendi id nostrum dolores accusamus. Aut debitis sed eum omnis itaque sint ut.',
    rating: 3,
    delivery_rating: 4,
    order_rating: 4,
    update_date: '2018-10-12T07:00:00.000Z',
  },
  {
    id: 67,
    user_name: 'Eleonore.Blanda19',
    restaurant_name: 'Schmitt and Sons',
    content: 'Sed molestiae aliquid voluptatibus qui neque. Exercitationem occaecati nobis temporibus nihil. Sed omnis voluptatem. Debitis est quod numquam delectus.',
    rating: 3,
    delivery_rating: 3,
    order_rating: 1,
    update_date: '2018-10-11T07:00:00.000Z',
  },
  {
    id: 65,
    user_name: 'Carter.Wolff',
    restaurant_name: 'Schmitt and Sons',
    content: 'Aspernatur veritatis rem autem possimus commodi quia et est. Sequi dolores omnis non. Et voluptas esse et sapiente harum nobis et placeat. Est excepturi aliquid sunt. Reiciendis aut cumque doloribus. Soluta eligendi ipsam facilis sit.',
    rating: 4,
    delivery_rating: 5,
    order_rating: 5,
    update_date: '2018-09-18T07:00:00.000Z',
  },
  {
    id: 128,
    user_name: 'Evert59',
    restaurant_name: 'Schmitt and Sons',
    content: 'A quia voluptatem aspernatur. Architecto quisquam expedita maxime et qui minima quis inventore.',
    rating: 2,
    delivery_rating: 2,
    order_rating: 5,
    update_date: '2018-09-10T07:00:00.000Z',
  },
  {
    id: 142,
    user_name: 'Davin6',
    restaurant_name: 'Schmitt and Sons',
    content: 'Qui adipisci itaque sit non aspernatur nostrum. Et deleniti aut. Consectetur facere quis. Aspernatur quo provident accusamus vel quia sint. Fugiat accusamus eligendi. Omnis doloremque odio minus a incidunt.',
    rating: 5,
    delivery_rating: 2,
    order_rating: 2,
    update_date: '2018-08-28T07:00:00.000Z',
  },
  {
    id: 205,
    user_name: 'Rebeka.Turcotte56',
    restaurant_name: 'Schmitt and Sons',
    content: 'Reprehenderit aut dolorum totam repellendus ut dolorum. Exercitationem porro consequatur qui dolores sit. Provident ipsa enim nihil error laborum. Omnis est est et iure laudantium voluptates corrupti quidem voluptates.',
    rating: 5,
    delivery_rating: 4,
    order_rating: 2,
    update_date: '2018-08-25T07:00:00.000Z',
  },
  {
    id: 273,
    user_name: 'Rebeka.Turcotte56',
    restaurant_name: 'Schmitt and Sons',
    content: 'Ullam sunt numquam ipsa unde assumenda in enim velit commodi. Aut magnam rerum eum. Officiis rerum ducimus. Aliquam quia iure quis rerum sed culpa assumenda dolore nihil.',
    rating: 2,
    delivery_rating: 2,
    order_rating: 2,
    update_date: '2018-08-21T07:00:00.000Z',
  },
  {
    id: 15,
    user_name: 'Brant.Skiles',
    restaurant_name: 'Schmitt and Sons',
    content: 'Quibusdam quia explicabo ut laudantium. Illum consequatur consequatur eum alias et non nisi doloribus facere.',
    rating: 1,
    delivery_rating: 2,
    order_rating: 2,
    update_date: '2018-08-19T07:00:00.000Z',
  },
  {
    id: 101,
    user_name: 'Juanita63',
    restaurant_name: 'Schmitt and Sons',
    content: 'Et consequatur dolorem saepe qui itaque a mollitia commodi nihil. Sit sed provident sed sed adipisci necessitatibus magni aperiam. Accusamus libero nisi consequatur eos dolores corporis in sunt.',
    rating: 2,
    delivery_rating: 4,
    order_rating: 4,
    update_date: '2018-07-10T07:00:00.000Z',
  },
  {
    id: 19,
    user_name: 'Raoul.Boehm',
    restaurant_name: 'Schmitt and Sons',
    content: 'Omnis magni facere deleniti voluptatem ut a iusto recusandae. Quibusdam occaecati odit fugit suscipit consequuntur. Eius laborum voluptatem vero quo impedit ad itaque mollitia tempora. Consequatur sed tenetur aut at enim quia. Repellat omnis corporis. Aliquam dolorem maxime aut dicta nulla est et.',
    rating: 1,
    delivery_rating: 3,
    order_rating: 5,
    update_date: '2018-06-22T07:00:00.000Z',
  },
  {
    id: 119,
    user_name: 'Doug.Rempel55',
    restaurant_name: 'Schmitt and Sons',
    content: 'Sint voluptatem reiciendis aliquid et et excepturi unde. Nam alias architecto deleniti. Ut fugit placeat et cum aperiam. Voluptatem sed quia maxime.',
    rating: 1,
    delivery_rating: 5,
    order_rating: 4,
    update_date: '2018-06-10T07:00:00.000Z',
  },
  {
    id: 192,
    user_name: 'Elenora63',
    restaurant_name: 'Schmitt and Sons',
    content: 'Delectus eveniet est voluptas quidem consequatur distinctio corrupti. Placeat deleniti et qui illo ut aut et aspernatur qui. At veritatis aut voluptatem.',
    rating: 2,
    delivery_rating: 4,
    order_rating: 1,
    update_date: '2018-06-07T07:00:00.000Z',
  },
  {
    id: 94,
    user_name: 'Esmeralda.Kub',
    restaurant_name: 'Schmitt and Sons',
    content: 'Adipisci sit labore. Et ducimus ducimus facilis quo. Id omnis ex illo error dolorem eius. Amet eum molestias rerum perferendis quibusdam sunt possimus et enim.',
    rating: 1,
    delivery_rating: 2,
    order_rating: 3,
    update_date: '2018-05-26T07:00:00.000Z',
  },
  {
    id: 44,
    user_name: 'Joseph_OConner',
    restaurant_name: 'Schmitt and Sons',
    content: 'Doloribus quis quibusdam aut voluptas exercitationem quia enim eos. Unde fuga architecto. Fugit fugiat tempore quisquam ut. In neque non non natus provident mollitia voluptas eveniet omnis.',
    rating: 4,
    delivery_rating: 4,
    order_rating: 4,
    update_date: '2018-05-14T07:00:00.000Z',
  },
  {
    id: 99,
    user_name: 'Evert59',
    restaurant_name: 'Schmitt and Sons',
    content: 'Non quos molestiae sed iure consequatur. Aut quam nam aut enim ipsum tempora nobis at non. Voluptatibus autem deleniti impedit. Quasi tenetur ea officia inventore facilis harum ab porro.',
    rating: 2,
    delivery_rating: 4,
    order_rating: 4,
    update_date: '2018-05-10T07:00:00.000Z',
  },
  {
    id: 269,
    user_name: 'Sallie29',
    restaurant_name: 'Schmitt and Sons',
    content: 'Odit molestiae ab eum enim quidem et. Nemo magni ut. Voluptate quae deserunt minima et inventore dicta. Nemo doloribus sit vel. Repudiandae saepe impedit dolor velit doloribus.',
    rating: 5,
    delivery_rating: 2,
    order_rating: 3,
    update_date: '2018-05-04T07:00:00.000Z',
  },
  {
    id: 198,
    user_name: 'Davin6',
    restaurant_name: 'Schmitt and Sons',
    content: 'Unde rerum dignissimos exercitationem sed corrupti. Unde voluptas incidunt est aut illum possimus et. Quis ducimus commodi aliquid sed et eos soluta voluptate. Magnam quis impedit cumque molestiae est. Aspernatur molestias quia saepe aliquam corporis vitae. Placeat quas minus eum eius qui.',
    rating: 4,
    delivery_rating: 5,
    order_rating: 3,
    update_date: '2018-04-14T07:00:00.000Z',
  },
  {
    id: 234,
    user_name: 'Elaina.Bernhard10',
    restaurant_name: 'Schmitt and Sons',
    content: 'Enim quos voluptatem nam voluptatibus voluptas. Molestiae et et dolorem.',
    rating: 2,
    delivery_rating: 1,
    order_rating: 1,
    update_date: '2018-03-26T07:00:00.000Z',
  },
  {
    id: 51,
    user_name: 'Markus23',
    restaurant_name: 'Schmitt and Sons',
    content: 'Necessitatibus aut atque illum adipisci quod nostrum dolor eos aut. Sit rerum nostrum pariatur corrupti ea voluptas et nihil. Ut porro aut hic corporis et molestias.',
    rating: 3,
    delivery_rating: 1,
    order_rating: 4,
    update_date: '2018-02-25T08:00:00.000Z',
  },
  {
    id: 118,
    user_name: 'Jennifer_Bradtke0',
    restaurant_name: 'Schmitt and Sons',
    content: 'Veniam qui esse tenetur rerum perferendis. Illum dicta dolor aut cum ea optio et voluptates. Ut omnis consequuntur. Voluptatem impedit vitae blanditiis quis fugit.',
    rating: 4,
    delivery_rating: 5,
    order_rating: 1,
    update_date: '2018-01-20T08:00:00.000Z',
  },
  {
    id: 220,
    user_name: 'Marcelle43',
    restaurant_name: 'Schmitt and Sons',
    content: 'Distinctio architecto voluptates cum error nisi et qui fugiat. Nihil porro eos velit qui. Et vel ea mollitia. Accusamus ut dolorum occaecati est itaque quis. Deleniti placeat at sint et enim eius. Dolor repellendus itaque aut reprehenderit assumenda sit aut modi.',
    rating: 3,
    delivery_rating: 3,
    order_rating: 4,
    update_date: '2018-01-08T08:00:00.000Z',
  },
  {
    id: 2,
    user_name: 'Rashawn.Sanford25',
    restaurant_name: 'Schmitt and Sons',
    content: 'Aut dolorem alias praesentium sequi optio rerum eligendi ipsum. Libero voluptatem ut iste praesentium molestias. Nemo fugit quia quia et voluptatem. Voluptatem sapiente in rerum a repellat omnis.',
    rating: 4,
    delivery_rating: 3,
    order_rating: 3,
    update_date: '2018-01-05T08:00:00.000Z',
  },
  {
    id: 130,
    user_name: 'Myles.Koss',
    restaurant_name: 'Schmitt and Sons',
    content: 'Cumque saepe fugiat ab. Sint repellendus aut nobis dolor enim ut ut iste magnam.',
    rating: 5,
    delivery_rating: 3,
    order_rating: 5,
    update_date: '2018-01-03T08:00:00.000Z',
  },
  {
    id: 32,
    user_name: 'Abbigail.Strosin89',
    restaurant_name: 'Schmitt and Sons',
    content: 'Ipsum reiciendis eaque laboriosam in et alias sequi rem eaque. Odio dolor non non reprehenderit odio dolor quasi nam. Quod sed consequatur perferendis quo minus voluptatum. Impedit sunt ut doloremque. Facilis delectus ipsa autem facilis veritatis.',
    rating: 3,
    delivery_rating: 5,
    order_rating: 2,
    update_date: '2017-12-31T08:00:00.000Z',
  },
];

export default sampleData;
